apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  selector:
    matchLabels:
      service: backend-label
  replicas: 1
  template:
    metadata:
      labels:
        service: backend-label
    spec:
      containers:
        - name: backend-dns-label
          image: devspace-talk-backend-image
          # TODO: move this configuration to a place that can be specified for
          # dev and prod differently
          env:
            - name: DATABASE_URL
              value: 'postgres://backend_user:backend_password@database-service/backend_db'
            - name: FLASK_APP
              value: 'run:app'
            - name: FLASK_RUN_HOST
              value: '0.0.0.0'
            - name: FLASK_RUN_PORT
              value: '5000'
            - name: FLASK_ENV
              value: development
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  ports:
    - port: 5000
      protocol: TCP
  selector:
    service: backend-label
  type: LoadBalancer
